"""Type definitions for langid."""

from typing import Tuple

def classify(text: str) -> Tuple[str, float]: ...
def set_languages(languages: list[str]) -> None: ...
def rank(text: str) -> list[Tuple[str, float]]: ...
