def classify(text: str) -> tuple[str, float]: ...
def rank(text: str) -> list[tuple[str, float]]: ...

class LanguageIdentifier:
    @classmethod
    def from_modelstring(cls, model: str, *, norm_probs: bool = ...) -> LanguageIdentifier: ...
    def classify(self, text: str) -> tuple[str, float]: ...
    def rank(self, text: str) -> list[tuple[str, float]]: ...
